"""update post default value

Revision ID: 482c7561cde3
Revises: 945f505bcbf6
Create Date: 2018-01-25 20:58:43.412377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482c7561cde3'
down_revision = '945f505bcbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_publish_date'), 'posts', ['publish_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_publish_date'), table_name='posts')
    # ### end Alembic commands ###
