"""rename User column: password to password_hash

Revision ID: 4df642f9746e
Revises: 43297e7634a2
Create Date: 2018-01-23 10:25:54.195638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df642f9746e'
down_revision = '43297e7634a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('password_hash')
    # ### end Alembic commands ###
