"""add gravatar_hash column for user model

Revision ID: 945f505bcbf6
Revises: f5a0e5d0065c
Create Date: 2018-01-25 19:14:16.725128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945f505bcbf6'
down_revision = 'f5a0e5d0065c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gravatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gravatar_hash')
    # ### end Alembic commands ###
